/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M11
 * Generated at: 2016-11-11 01:52:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package com.czfshine.tellme;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class mange_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.0.M11/lib/standard.jar!/META-INF/sql.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/C:/apache-tomcat-9.0.0.M11/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("file:/C:/apache-tomcat-9.0.0.M11/lib/standard.jar", Long.valueOf(1098736424000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- head -->\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap-combined.min.css\">\r\n");
      out.write("<script src=\"./js/jquery-2.0.0.min.js\"></script>\r\n");
      out.write("<script src=\"./js/jquery-ui.js\"></script>\r\n");
      out.write("<script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function post(URL, PARAMS) {\r\n");
      out.write("\t $.ajax({\r\n");
      out.write("         \"type\" : 'post',\r\n");
      out.write("         \"url\" : URL,\r\n");
      out.write("         \"dataType\" : \"json\",\r\n");
      out.write("         \"data\" : PARAMS,\r\n");
      out.write("         \"success\" : function(resp) {\r\n");
      out.write("         },\r\n");
      out.write("         \"error\":function(emsg){\r\n");
      out.write("         }\r\n");
      out.write("     });\r\n");
      out.write("\t \r\n");
      out.write("\t}\r\n");
      out.write("function del(id){\r\n");
      out.write("\tpost('./data.jsp',{type:0,id:id});\r\n");
      out.write("\t$(\"#\"+id).hide();\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<title>鍙戣█鏉�</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<!--  12绛夊垎 2:6:4 -->\r\n");
      out.write("\t\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t\t<!-- left -->\r\n");
      out.write("\t\t\t\t\t<div class=\"span2\"></div>\r\n");
      out.write("\t\t\t\t\t<!-- center -->\r\n");
      out.write("\t\t\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t\t\t<!-- 鏍囬 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									String type = request.getParameter("username");
									int p = Integer.parseInt(request.getParameter("p"));
									out.println(type);
								
      out.write("<small>鐨勫彂瑷�鏉�</small>\r\n");
      out.write("\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 鍐呭 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t\t\t");

								Class.forName("com.mysql.jdbc.Driver");
								Connection con = DriverManager.getConnection(
										"jdbc:mysql://localhost:3306/PLANE?useUnicode=true&characterEncoding=utf-8", "root", "12345678");
								PreparedStatement ps = con.prepareStatement("SELECT count(*)  FROM data WHERE fromuser=\'" + type + "\';");
								ResultSet rs = ps.executeQuery();
								rs.next();
								int count=rs.getInt(1);
								int pages=0,max=4;
								pages=count/max ;
								//out.println(count);
								ps = con.prepareStatement("SELECT *  FROM data WHERE fromuser=\'" + type + "\' limit "+(p-1)*max+","+max+";");
								rs = ps.executeQuery();
								String last="";
								while (rs.next()) {
									String fromuser = rs.getString("touser");
									String commit = rs.getString("commit");
									if(!fromuser.equals(last)){
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a rel=\"nofollow\" href=\"./chat.jsp?username=");
out.println(type); 
      out.write("&touser=");
out.println(fromuser); 
      out.write("\" class=\"list-group-item active\"> \r\n");
      out.write("\t\t\t\t\t\t\t");

 										out.println(fromuser);
										
							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t");

										last=fromuser;}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"");
out.print( rs.getInt("id")); 
      out.write("\" class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"list-group-item-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									out.println(commit);
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t <button onclick=\"del(");
 out.println( rs.getInt("id"));
      out.write(")\" type=\"button\" class=\"btn btn-danger  btn-sm right nofollow\">鍒犻櫎</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge\">14</span>甯姪\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<a rel=\"nofollow\" class=\"list-group-item active\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"badge\">14</span>甯姪</a>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pagination nofollow\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(p!=1){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a rel=\"nofollow\" href=\"./mange.jsp?username=");
out.print(type); 
      out.write('&');
      out.write('p');
      out.write('=');
out.print(p-1); 
      out.write("\">涓婁竴椤�</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
for(int i=1;i<=pages;i++){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a rel=\"nofollow\" href=\"./mange.jsp?username=");
out.print(type); 
      out.write('&');
      out.write('p');
      out.write('=');
out.print(i); 
      out.write('"');
      out.write('>');
out.print(i); 
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t");
if(p!=pages && pages>1){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a rel=\"nofollow\" href=\"./mange.jsp?username=");
out.print(type); 
      out.write('&');
      out.write('p');
      out.write('=');
out.print(p+1); 
      out.write("\">涓嬩竴椤�</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- RIGHT -->\r\n");
      out.write("\t\t\t\t\t<div class=\"span4\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-search\" action=\"./chat.jsp\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"input-medium search-query\" type=\"text\" name=\"touser\" />\r\n");
      out.write("\t\t\t\t\t\t\t<input class=\"hide input-medium search-query\" value=\"");
out.println(type); 
      out.write("\" type=\"text\" name=\"username\" />\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">闂��</button>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t <a  href=\"./plane.jsp?username=");
out.print(type); 
      out.write("&p=1\" ><button type=\"button\" class=\"btn btn-primary  btn-sm right nofollow\">鏌ョ湅鐣欒█</button>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
